# Generated by Django 5.0 on 2024-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_venue_venue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
