# Generated by Django 5.0.1 on 2024-01-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_wish_alter_guest_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Last Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=120, verbose_name="First Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Adress"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="First Name")),
            ],
        ),
    ]
