# Generated by Django 5.0.1 on 2024-01-24 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_artist_contact_tour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="tour",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.date(2024, 1, 24), verbose_name="Arrival Date"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.artist",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.contact",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="departure_date",
            field=models.DateTimeField(
                default=datetime.date(2024, 1, 24), verbose_name="Departure Date"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="description",
            field=models.TextField(
                max_length=120, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=120, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Tour summary"),
        ),
    ]
